apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanarr-job
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cleanarr-job
            image: ghcr.io/example/cleanarr-cronjob:v0.2.3
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: cleanarr-secrets
            - configMapRef:
                name: cleanarr-config
            volumeMounts:
            - name: logs
              mountPath: /logs
          volumes:
          - name: logs
            emptyDir: {}
